services:
  - type: web
    name: museheart_music
    env: python
    plan: free
    repo: https://github.com/zRitsu/MuseHeart-MusicBot.git
    buildCommand: pip3 install -r requirements.txt --no-cache-dir
    startCommand: python3 main.py
    envVars:
      - key: TOKEN_BOT_1
        sync: false
      - key: TOKEN_BOT_2
        sync: false
      - key: TOKEN_BOT_3
        sync: false
      - key: DEFAULT_PREFIX
        sync: false
      - key: MONGO
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: MONGO_SSL_FIX
        value: true
      - key: PLAYER_SESSIONS_MONGODB
        value: true
      - key: AUTO_DOWNLOAD_LAVALINK_SERVERLIST
        value: true
    autoDeploy: false # optional
